const T_DEMOS = {
  'pt-br': {
    mediaHint: 'Arraste os sliders. Adicione um valor extremo e veja a média ser "puxada" para cima ou para baixo.',
    valorA: 'Valor A', valorB: 'Valor B', valorC: 'Valor C', valorD: 'Valor D',
    outlier: 'Outlier', incluirOutlier: 'Incluir outlier', soma: 'Soma',
    qtd: 'Quantidade (n)', media: 'Média',
    passo1: 'Passo 1: valores embaralhados — ordene para achar o centro',
    passo2: 'Passo 2: ordenado — o centro é a mediana',
    ordenarVal: 'Ordenar valores →', resetar: 'Resetar',
    valorX: 'Valor ', addValor: '+ Adicionar valor', remValor: '− Remover último',
    mediana: 'Mediana', impar: 'ímpar', par: 'par', meio: 'meio',
    posicao: 'posição', mediaCentrais: 'média dos dois valores centrais',
    repeticoes: 'Repetições', exProvas: 'Exemplo: notas de prova',
    aparece: 'aparece', vezes: '×', nenhumVal: 'nenhum valor',
    definaPeloMenos: 'Defina pelo menos um valor com repetições > 0.',
    semModa: 'Sem moda única', empatam: 'todos os valores ativos empatam na frequência.',
    moda: 'Moda', maiorFreq: 'maior frequência',
    multimodal: 'Distribuição multimodal: modas =', conjExp: 'Conjunto expandido',
    modaHint: 'Ajuste os valores: quando dois ou mais empatarem na contagem, você pode ter mais de uma moda — ou nenhuma, se todos aparecerem igualmente.',
    llmTokenizerH: 'Tokenizer Playground',
    llmTokenizerP: 'Digite uma frase e veja como um texto longo pode ser quebrado em partes menores.',
    llmTokGen: 'Tokens gerados',
    llmTokIdea: 'Ideia principal: o modelo lê pedaços de texto, não necessariamente palavras completas.',
    llmNextH: 'Predict Next Token',
    llmNextP: 'Escolha um contexto e veja como o modelo distribui probabilidade entre possíveis continuações.',
    llmNextBtn: 'Gerar próximo token',
    llmNextClick: 'Clique em <strong>Gerar próximo token</strong> para simular a escolha.',
    contexto: 'Contexto',
    tokenEsc: 'Token escolhido',
    llmNextDesc: 'O modelo não recupera uma resposta pronta: ele escolhe uma continuação plausível e continua o processo a partir dela.',
    llmEmbH: 'Embeddings Visualizer',
    llmEmbP: 'Escolha um concepto e veja vizinhos semânticos próximos no espaço vetorial.',
    llmEmbL1: 'Leitura intuitiva: embeddings aproximam tokens que aparecem em contextos parecidos.',
    llmEmbL2: 'Importante: proximidade vetorial não é "entendimento humano", mas ajuda o modelo a generalizar relações.',
    llmAttH: 'Attention Visualizer',
    llmAttP: 'Clique em uma palavra para ver quais outras partes da frase recebem mais atenção.',
    llmAttL1: 'Leitura: attention não é magia; é um jeito matemático de medir relevância entre partes da sequência.',
    llmAttL2: 'Exemplo: o pronome', llmAttL3: 'depende de outras palavras para ser interpretado.',
    llmCtxH: 'Visualizador da janela de contexto',
    llmCtxP: 'Adicione texto e observe a janela de contexto encher. Quando ela passa do limite, as partes mais antigas perdem espaço.',
    llmCtxUso: 'Uso da janela', llmCtxChar: 'caracteres simulados',
    llmCtxOk: 'Ainda há espaço para contexto recente.',
    llmCtxFull: 'Limite atingido: mensagens mais antigas precisam ser resumidas ou descartadas.',
    llmTempH: 'Temperature Demo',
    llmTempP: 'Arraste o slider para ver como a distribuição de probabilidade fica mais concentrada ou mais espalhada.',
    temperatura: 'Temperatura',
    llmTempL: 'Leitura: temperatura baixa concentra probabilidade nos candidatos mais fortes.',
    llmTempM: 'Leitura: temperaturas intermediárias equilibram previsibilidade e variedade.',
    llmTempHgh: 'Leitura: temperatura alta espalha a distribuição e aumenta a chance de saídas inesperadas.',
    sysMsg: 'Sistema: responda de forma didática.',
    usrMsg1: 'Usuário: explique transformers.',
    astMsg1: 'Assistente: transformer usa attention para relacionar tokens.',
    usrMsg2: 'Usuário: agora compare com RNNs.',
    astMsg2: 'Assistente: RNNs processam sequências de modo mais serial.',
    usrPre: 'Usuário: ',
    pyVarTitle: 'Playground: Variáveis e Tipos',
    pyVarHint: 'Digite um valor e veja o tipo detectado pelo Python.',
    pyVarName: 'Nome da variável',
    pyVarValue: 'Valor',
    pyVarAssign: 'Atribuir →',
    pyVarReset: 'Limpar',
    pyVarMemory: 'Memória',
    pyVarOutput: 'Saída',
    pyVarType: 'Tipo',
    pyVarTip: '💡 Dica: Python infere o tipo automaticamente — não é necessário declarar.',
    pyVarErrName: 'Nome inválido (use apenas letras, números e _)',
    pyVarErrEmpty: 'Digite um valor para a variável.'
  }
};